### ISSUE TITLE
Liên kết giao diện và chức năng

### ISSUE THREAD

**Issue by honggaj** [tamntm39/TreeStore.FE#32]
Xem, thêm, sửa, xóa CÂY : Minh Tâm
Xem, sửa, xóa LOẠI CÂY: Bảo Khang
Xem, xóa ĐÁNH GIÁ: Khánh Đăng

**Comment by tamntm39** [comment]
Thêm loại cây, chỉnh sửa loại cây, xóa loại cây : Done
